version: '2'

services:

   jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
   # volumes:
    #  - /home/jenkins_home:/var/jenkins_home
     # - /var/run/docker.sock:/var/run/docker.sock
    #environment:
     # JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"

   sonarqube:
    image: sonarqube
    container_name: sonar
   # volumes:
     # - /home/jenkins_home:/var/jenkins_home
     # - /var/run/docker.sock:/var/run/docker.sock
     #environment:
     # JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "9000:9000"

   nexus:
    image: sonatype/nexus
    container_name: nexus
    #volumes:
     # - /home/jenkins_home:/var/jenkins_home
     # - /var/run/docker.sock:/var/run/docker.sock
    #environment:
     # JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8081:8081"
